server:
   port: 8081
   servlet:
      context-path: /

   tomcat:
      basedir: /temp/logs
      accesslog:
          enabled: true
          pattern: "%t %a %r %s (%D ms)"

   sinablog:
       token: breakingpoint
       clientId: wxd0296c8737a1015c
       redirectUri: afde8500f53a37470b64cf24551d5721
       encodingAESKey: Ex9SZPntYS7SYtU8Vmgq6yu9xEVIwc6mEwhLznxdlBj
       accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
       wechatServerHost: http://aaron.tunnel.qydev.com/
       verifyCdMin: 30
       sinaUrl: #访问sinablog服务器
            oauthUrl: https://api.weibo.com/oauth2/authorize?client_id=CLIENTID&redirect_uri=REDIRECTURI
            oauthAccessTokenGetUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code


spring:
    datasource:
        name: dev
        url: jdbc:mysql://127.0.0.1:3306/automobile?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath:config/sqlmap/*.xml
  type-aliases-package: com.breakingpoint.automobile.bean
  config-location: classpath:config/mybatis-config.xml

logging:
   path: /temp/logs
#   config: classpath:logback.groovy
   pattern:
      console: "%d %-4r [%t] %-5p %c - %m %n"
   level:
      com.breakingpoint.automobile.controller: INFO
      com.breakingpoint.automobile.service: INFO
      com.breakingpoint.automobile.mapper: DEBUG
      org.springframework.web: DEBUG
      org.mybatis: INFO
    #file: /temp/logs/project.log

